version: '3.8'
services:
  cas-service:
    build: .
    container_name: cas-service
    ports:
      - "8081:8080"
    networks:
      - sakai_network_dev
    restart: always

networks:
  sakai_network_dev:
    external: true
