version: '3.8'
services:
  cas-service:
    build: .
    container_name: cas-service
    ports:
      - "8080:8081"  # Cambié el puerto para reflejar tu CAS en el puerto 8081
    restart: always
    networks:
      - sakai_network_dev
networks:
  sakai_network_dev:
    external: true
