# Configuración del servidor CAS
#cas:
#  server:
#    name: http://localhost:8080
#    prefix: ${cas.server.name}/cas
#  authn:
#    jdbc:
#      query[0]:
#        sql: SELECT CONVERT(varchar(34),uwd2, 1) AS clave FROM usuario_general_login WHERE state='1' AND us=?
#        driverClass: com.microsoft.sqlserver.jdbc.SQLServerDriver
#        url: jdbc:sqlserver://172.16.1.85:1433;databaseName=academia3000_john
#        fieldPassword: clave
#        user: johndavidg
#        password: JDgc9714(Y)
#
## Configuración de la base de datos
#spring:
#  datasource:
#    url: jdbc:sqlserver://172.16.1.85:1433;databaseName=academia3000_john
#    username: johndavidg
#    password: JDgc9714(Y)
#    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver

info:
  description: CAS Configuration